server:
  port: 8089

spring:
  application:
    name: promo-service

  data:
    mongodb:
      uri: ${MONGODB_URI}/promodb?authSource=admin
      auto-index-creation: true

order:
  service:
    url: ${ORDER_SERVICE_URL}
