server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    cart:
      url: jdbc:mysql://localhost:3307/cartdb
      username: admin
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver

    order:
      url: jdbc:mysql://localhost:3307/orderdb
      username: admin
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver

    wishlist:
      url: jdbc:mysql://localhost:3307/wishlistdb
      username: admin
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health


  mail:
    host: smtp.gmail.com
    port: 587
    username: rishi.nihal.singh@gmail.com
    password: esmodbcttsuathlt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true