server:
  port: 8085


spring:
  application:
    name: inventory-service

  datasource:
    url: ${MYSQL_URI}/inventorydb
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000        # 30 sec
      max-lifetime: 120000       # 2 min (IMPORTANT)
      connection-timeout: 30000
      validation-timeout: 5000
      keepalive-time: 30000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
