server:
  port: 8084

spring:
  application:
    name: product-catalog-service

  data:
    mongodb:
      uri: mongodb://admin:admin@107.21.164.204:27017/productdb?authSource=admin
      auto-index-creation: true
    opensearch:
      index: products

  elasticsearch:
    uris: 107.21.164.204

  kafka:
    bootstrap-servers: 107.21.164.204:29092
    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


aws:
  region: ap-east-1
  s3:
    bucket: product-images

inventory:
  service:
    url: http://localhost:8085

keycloak:
  issuer-url: https://107.21.164.204:8443/realms/master