server:
  port: 8084

spring:
  application:
    name: product-catalog-service

  data:
    mongodb:
      uri: ${MONGODB_URI}/productdb?authSource=admin
      auto-index-creation: true
    opensearch:
      index: products

  elasticsearch:
    uris: ${ELASTIC_SEARCH_URI}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


aws:
  region: ap-east-1
  s3:
    bucket: product-images

inventory:
  service:
    url: ${INVENTORY_SERVICE_URI}

keycloak:
  issuer-url: ${KEYCLOAK_ISSUER_URL}