name: CI Backend

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build all services
        working-directory: backend
        run: mvn clean install -DskipTests=true